### ISSUE TITLE
Support for RTL8195AM & RTL8710 Chipsets

### ISSUE THREAD

**Issue by boseji** [Marzogh/Travis-CI#3]
Hi,

I wish to add the RTL8195AM & RT8710 Ameaba Platforms support to this install script.
Not very well aware Travis. But I can learn with your help.
It would be helpful to extend testing portfolio for all types of Arduino based IoT platforms.

To start here is the URL to be added for the JSON:
https://github.com/Ameba8195/Arduino/raw/master/release/package_realtek.com_ameba_index.json

Let me know how to go about this.
Also I wish to use your script to run my Travis CI.

Thanks again for the great code ,

Regards,
boseji

**Comment by Marzogh** [comment]
All done and sorted. :) Release > v1.1.0 has the ameba boards added to the list.

My Travis CI script is just a shell script that runs on a Debian container somewhere in Travis' cloud infrastructure. All Arduino related commands in there are standard Arduino CLI stuff. (Have you used Arduino via CLI on Linux before? Its fun! :) )

**Comment by boseji** [comment]
Thanks for your help. I will try out too.

**Comment by Marzogh** [comment]
Anytime!
